#!/bin/bash -xe

# upgrade server (retry if network is not ready
for i in 1 2 3 4 5; do
  apt-get update && break || sleep 10;
done
DEBIAN_FRONTEND=noninteractive apt-get -yq -o Dpkg::Options::="--force-confdef" upgrade

# doing os hardening
# https://github.com/dev-sec/puppet-os-hardening

wget https://apt.puppetlabs.com/puppet-release-focal.deb
dpkg -i puppet-release-focal.deb || exit 1
rm -f puppet-release-focal.deb

apt-get update
apt-get -yq install puppet-agent

systemctl stop puppet
systemctl disable puppet
/opt/puppetlabs/bin/puppet module install hardening-os_hardening || exit 1

cat > hardening.pp << EOF
class { 'os_hardening':
  enable_ipv4_forwarding => true,
}
EOF

/opt/puppetlabs/bin/puppet apply hardening.pp || exit 1
rm -f hardening.pp

# install k3s as worker node
if [ "${k3s_version}" == "latest" ] || [ "${k3s_version}" == "stable" ]; then
  curl -svfL4 --retry 100 https://get.k3s.io | INSTALL_K3S_CHANNEL=${k3s_version} K3S_URL=https://${rancher_host}.${rancher_domain}:6443 K3S_TOKEN=${token} sh -
else
  curl -svfL4 --retry 100 https://get.k3s.io | INSTALL_K3S_VERSION=${k3s_version} K3S_URL=https://${rancher_host}.${rancher_domain}:6443 K3S_TOKEN=${token} sh -
fi
